/obj/item/gravedecor
	name = "decoracion de tumbas"
	desc = "Si estas viendo esto, grita a los codificadores."
	icon = 'icons/roguetown/items/graveitems.dmi'
	icon_state = "headstone_basic"
	gripped_intents = null
	possible_item_intents = list(INTENT_GENERIC)
	w_class = WEIGHT_CLASS_NORMAL
	resistance_flags = FIRE_PROOF
	/// This applies a gravequality bonus when added to a grave. 1 means a CHEAP decoration, usually wood. 2 means a MODERATE decoration, usually masoned stone.
	/// 3 means an EXPENSIVE decoration, usually forged.
	var/decorationquality
	/// Set this if this decoration is not crafted/doesn't have an item state, but instead is made by using a non decoration item on a grave. MUST BE TYPE
	var/sourceitem
	/// Patrons associated with this grave decoration. Usually a headstone.
	var/list/patrons

/obj/item/gravedecor/Initialize(mapload, parent)
	. = ..()
	if(parent)
		sourceitem = parent

/obj/item/gravedecor/examine(mob/user)
	. = ..()

	if(decorationquality == 1)
		. += span_info("Esta es una decoracion tosca.")
	if(decorationquality == 2)
		. += span_info("Esta es una decoracion mediana.")
	if(decorationquality == 3)
		. += span_info("Esta decoracion es de la mas alta calidad.")
	if(length(patrons))
		if(/datum/patron/divine/astrata in patrons)
			. += SPAN_GOD_ASTRATA("Esta decoracion venera a Astrata, el Tirano del Sol.")
		if(/datum/patron/divine/noc in patrons)
			. += SPAN_GOD_NOC("Esta decoracion venera a Noc, el Principe de la Luna.")
		if(/datum/patron/divine/abyssor in patrons)
			. += SPAN_GOD_ABYSSOR("Esta decoracion venera a Abyssor, Señor de las Profundidades.")
		if(/datum/patron/divine/dendor in patrons)
			. += SPAN_GOD_DENDOR("Esta decoracion venera a Dendor, el Padre de las Bestias.")
		if(/datum/patron/divine/necra in patrons)
			. += SPAN_GOD_NECRA("Esta decoracion venera a Necra, la doncella de los infiernos.")
		if(/datum/patron/divine/ravox in patrons)
			. += SPAN_GOD_RAVOX("Esta decoracion venera a Ravox, la Encarnacion de la Justicia.")
		if(/datum/patron/divine/xylix in patrons)
			. += SPAN_GOD_XYLIX("Esta decoracion venera a Xylix, el de lengua plateada.")
		if((/datum/patron/divine/pestra || /datum/patron/alternate/wurm) in patrons)
			. += SPAN_GOD_PESTRA("Esta decoracion venera a Pestra, el Portador de la Peste.")
		if(/datum/patron/divine/malum in patrons)
			. += SPAN_GOD_MALUM("Esta decoracion venera a Malum, el Gran Artesano.")
		if(/datum/patron/divine/eora in patrons)
			. += SPAN_GOD_EORA("Esta decoracion venera a Eora, el Patron del Amor.")
		if(/datum/patron/alternate/great_hunt in patrons)
			. += SPAN_GOD_GREATHUNT("Esta decoracion venera la Gran Caceria.")
		if(/datum/patron/psydon in patrons)
			. += SPAN_GOD_PSYDON("Esta decoracion venera a Psydon, el Dios Antiguo.")

/obj/item/gravedecor/headstone
	name = "lapida puntiaguda"
	desc = "Una lapida con un pico afilado y mucho espacio para una inscripcion."
	icon_state = "headstone_basic"
	decorationquality = 2

	/// Generated by burial_rites, what will be read on examine with grave or the headstone itself
	var/inscription
	/// Modified by by a chisel or short sharp object, allows for a small message to be added to inscription
	var/custom_message

/obj/item/gravedecor/headstone/examine(mob/user)
	. = ..()

	if(inscription)
		. += "<br>[inscription]"
		. += span_warning("Espera… ¿no deberia estar adjunto a una tumba?")
	else if(custom_message) // Not inscribed, but there is a custom_message
		. += span_info("Hay un mensaje tallado en \the [src]...<br>")
		. += span_italics("[custom_message]")


/obj/item/gravedecor/headstone/item_interaction(mob/living/user, obj/item/tool, list/modifiers)
	if(user.cmode)
		return NONE

	if(tool.wlength < WLENGTH_SHORT)
		return NONE

	if(!(tool.get_sharpness()))
		return NONE

	var/new_message = tgui_input_text(user, "¿Que te gustaria que estuviera inscrito en \the [src]?", "Inscripcion personalizada", custom_message, 150, TRUE)
	if(!new_message || new_message == custom_message)
		return ITEM_INTERACT_BLOCKING

	user.visible_message(span_info("[user] comienza a grabar un mensaje en \the [src] con \a [tool]."), span_info("Comienzas a grabar un mensaje en \the [src]."), span_info("Escuchas a alguien tallando piedra."))
	playsound(src, pick('sound/combat/hits/onrock/onrock (1).ogg', 'sound/combat/hits/onrock/onrock (2).ogg', 'sound/combat/hits/onrock/onrock (3).ogg', 'sound/combat/hits/onrock/onrock (4).ogg'), 100)
	if(!do_after(user, 5 SECONDS, src, progress=TRUE, display_over_user=TRUE))
		return ITEM_INTERACT_BLOCKING

	user.visible_message(span_info("[user] termina trabajando en \the [src]."), span_info("Termina de grabar \the [src] con tu mensaje."))
	custom_message = new_message
	return ITEM_INTERACT_SUCCESS

/obj/item/gravedecor/headstone/crude
	name = "lapida tosca"
	desc = ""
	icon_state = "headstone_crude"
	sourceitem = /obj/item/grown/log/tree/stick
	decorationquality = 1

/obj/item/gravedecor/headstone/obelisk
	name = "Obelisco de lapida"
	desc = "Una lapida alta con incrustaciones de hierro, para que tus obras nunca sean olvidadas."
	icon_state = "headstone_obelisk"
	dropshrink = 0.8
	decorationquality = 3

/obj/item/gravedecor/headstone/psydon
	name = "Lapida psydonic"
	desc = "Una lapida con forma de psycross puede ser considerada heretica por algunos, pero perturbar las tumbas sobre las que se encuentra aun mas."
	icon_state = "headstone_psydon"
	dropshrink = 0.8
	decorationquality = 2
	patrons = list(/datum/patron/psydon, /datum/patron/psydon/extremist)

/obj/item/gravedecor/headstone/astrata
	name = "Lapida astratan"
	desc = "La cruz dorada de Astrata, nada menos que para el Tirano del Sol."
	icon_state = "headstone_astrata"
	dropshrink = 0.8
	decorationquality = 3
	patrons = list(/datum/patron/divine/astrata)

/obj/item/gravedecor/headstone/pestra
	name = "lapida de pestran"
	desc = "Cualquier tumba en la que se encuentre practicamente esta pidiendo a gritos que la roben. Quizas esa sea la intencion."
	icon_state = "headstone_pestra"
	dropshrink = 0.8
	decorationquality = 2
	patrons = list(/datum/patron/divine/pestra, /datum/patron/alternate/wurm)

/obj/item/gravedecor/headstone/abyssor
	name = "lapida abissorita"
	desc = "No es una vision comun, la mayoria de los cadaveres se pierden en su abrazo salobre antes de que puedan ver tierra."
	icon_state = "headstone_abyssor"
	dropshrink = 0.8
	decorationquality = 2
	patrons = list(/datum/patron/divine/abyssor)

/obj/item/gravedecor/headstone/hunt
	name = "lapida del craneo"
	desc = "Una vision poco comun en estas tierras, aunque apenas se la puede llamar una lapida, es prestigiosa para quienes la ganan."
	icon_state = "headstone_hunt"
	dropshrink = 0.8
	decorationquality = 1
	patrons = list(/datum/patron/alternate/great_hunt, /datum/patron/alternate/great_hunt/proven)

/obj/item/gravedecor/headstone/necra
	name = "Lapida de Necran"
	desc = "A este se le acabo el tiempo. Quizas nunca tuvieron ninguno. ¿Realmente importa?"
	icon_state = "headstone_necra"
	dropshrink = 0.8
	decorationquality = 2
	patrons = list(/datum/patron/divine/necra)

/obj/item/gravedecor/headstone/malum
	name = "lapida de malumita"
	desc = "Es un trabajo pesado incluso instalar esto."
	icon_state = "headstone_malum"
	dropshrink = 0.8
	decorationquality = 3
	patrons = list(/datum/patron/divine/malum)

/obj/item/gravedecor/headstone/eora
	name = "Lapida eoran"
	desc = "Hecho para aquellos VERDADERAMENTE queridos difuntos."
	icon_state = "headstone_eora"
	dropshrink = 0.8
	decorationquality = 3
	patrons = list(/datum/patron/divine/eora)

/obj/item/gravedecor/gravefence
	name = "cerca de tumbas tosca"
	desc = "Una tosca valla hecha de guijarros sin forma, hecha para delimitar una tumba (mas o menos) exactamente."
	icon_state = "gravefence_stone"
	dropshrink = 0.8
	decorationquality = 1

/obj/item/gravedecor/gravefence/block
	name = "valla cincelada"
	desc = "Una valla de bloques para incrustar en la tierra, hecha para delimitar exactamente una tumba."
	icon_state = "gravefence_block"
	dropshrink = 0.8
	decorationquality = 2

/obj/item/gravedecor/gravefence/iron
	name = "valla de hierro"
	desc = "Una valla para tumbas de hierro forjado. Ominoso."
	icon_state = "gravefence_iron"
	dropshrink = 0.8
	decorationquality = 3
