/// How much does devotion increase for quality above 7. This is also the minimum amount of devotion a 'T3' grave will generate
#define GRAVE_DEVOTION_INCREMENT 0.025
/// Absolute max passive devotion Necrans can get from all graves.
#define GRAVE_DEVOTION_GLOBAL_MAX 0.5

/obj/structure/closet/dirthole
	name = "agujero"
	icon_state = "hole1"
	icon = 'icons/turf/constructed/grave.dmi'
	mob_storage_capacity = 3
	allow_dense = TRUE
	opened = TRUE
	density = FALSE
	anchored = TRUE
	can_buckle = FALSE
	resistance_flags = INDESTRUCTIBLE
	buckle_lying = 90
	layer = 2.8
	lock = null
	can_add_lock = FALSE
	alternative_icon_handling = TRUE
	/// How big the hole is, at 3 you can bury a body, at 4 theres something buried. Global defines in `misc.dm`
	var/stage = DIRTHOLE_SHALLOW

	/// Present headstone. If this is empty, there isnt one.
	var/obj/item/gravedecor/headstone/headstone
	/// Present gravefence. If this is empty, there isnt one.
	var/obj/item/gravedecor/gravefence/gravefence
	/// From 0-10. You shouldn't be able to get more than 10 quality. This is affected by the headstone, gravefence, location of burial, and if you used a winding sheet / coffin.
	var/gravequality = 0
	/// For debug/administrative purposes. Set this if you want it to apply next time we call update_quality.
	var/bonusquality = 0
	/// Has the "burial rites" miracle been used on this grave. TRUE or FALSE.
	var/is_consecrated = FALSE

	/// How much passive devotion is generated by this grave. Updated by `adjust_grave_necra_devotion()`
	var/necra_devotion_gain = 0
	/// If TRUE, no devotion is calculated for this dirthole. Useful for spawned bodies we don't want to count.
	var/no_devotion = FALSE

/obj/structure/closet/dirthole/Initialize()
	var/turf/open/floor/dirt/T = loc
	if(!istype(T))
		return INITIALIZE_HINT_QDEL
	if(T.muddy && stage != DIRTHOLE_GRAVE)
		if(!(locate(/obj/item/natural/worms) in T))
			if(prob(40))
				if(prob(10))
					new /obj/item/natural/worms/grub_silk(T)
				else
					new /obj/item/natural/worms/leech(T)
			else
				new /obj/item/natural/worms(T)
		if(!(locate(/obj/item/natural/clay) in T))
			if(prob(25))
				new /obj/item/natural/clay(T)
	else
		if(!(locate(/obj/item/natural/stone) in T))
			if(prob(23))
				new /obj/item/natural/stone(T)
	update_appearance(UPDATE_ICON | UPDATE_NAME)
	ADD_TRAIT(src, TRAIT_DO_NOT_SPLASH, INNATE_TRAIT)
	return ..()

/obj/structure/closet/dirthole/Destroy(force)
	// Remove passive devotion
	is_consecrated = FALSE
	adjust_grave_necra_devotion()
	qdel(headstone)
	qdel(gravefence)
	return ..()

/obj/structure/closet/dirthole/examine(mob/user)
	. = ..()
	if(headstone?.inscription)
		. += span_info("\A [headstone] esta arriba y lee lo siguiente...")
		. += headstone.inscription
	if(is_consecrated)
		switch(gravequality)
			if(0 to 3)
				user.add_stress(/datum/stress_event/saw_grave_1)
				user.remove_stress(/datum/stress_event/saw_grave_2)
				user.remove_stress(/datum/stress_event/saw_grave_3)
				user.remove_stress(/datum/stress_event/saw_grave_4)
			if(4 to 6)
				user.add_stress(/datum/stress_event/saw_grave_2)
				user.remove_stress(/datum/stress_event/saw_grave_1)
				user.remove_stress(/datum/stress_event/saw_grave_3)
				user.remove_stress(/datum/stress_event/saw_grave_4)
			if(7 to 9)
				user.add_stress(/datum/stress_event/saw_grave_3)
				user.remove_stress(/datum/stress_event/saw_grave_1)
				user.remove_stress(/datum/stress_event/saw_grave_2)
				user.remove_stress(/datum/stress_event/saw_grave_4)
			if(10)
				user.add_stress(/datum/stress_event/saw_grave_4)
				user.remove_stress(/datum/stress_event/saw_grave_1)
				user.remove_stress(/datum/stress_event/saw_grave_2)
				user.remove_stress(/datum/stress_event/saw_grave_3)

/obj/structure/closet/dirthole/grave
	stage = DIRTHOLE_PIT
	icon_state = "grave"

/obj/structure/closet/dirthole/closed
	stage = DIRTHOLE_GRAVE
	climb_offset = 10
	icon_state = "gravecovered"
	opened = FALSE

/// Right clicking with hand allows you to remove grave decorations if the grave has not been consecrated yet
/obj/structure/closet/dirthole/attack_hand_secondary(mob/user, list/modifiers)
	. = ..()
	if(. == SECONDARY_ATTACK_CANCEL_ATTACK_CHAIN)
		return

	if(stage != DIRTHOLE_GRAVE)
		return

	var/list/grave_decorations = list()
	if(headstone)
		grave_decorations += headstone
	if(gravefence)
		grave_decorations += gravefence

	// List formed, handle if empty, only one, or both
	var/obj/item/gravedecor/item_to_remove
	if(!grave_decorations)
		return SECONDARY_ATTACK_CANCEL_ATTACK_CHAIN
	else if(length(grave_decorations) != 1)
		item_to_remove = tgui_input_list(user, "¿Que decoracion quieres quitar?", "Eliminacion de decoracion de tumbas", grave_decorations)
	else
		item_to_remove = grave_decorations[1] // only one item

	if(!item_to_remove)
		return SECONDARY_ATTACK_CANCEL_ATTACK_CHAIN

	// Time to actually remove the item
	user.visible_message(span_info("[user] comienza a quitar \the <span class='bold'>[item_to_remove]</span> de \the [src]"), span_notice("Intenta quitar \the <span class='bold'>[item_to_remove]</span> de \the [src]"))
	playsound(src, 'sound/items/dig_shovel.ogg', 100, FALSE)
	if(!do_after(user, 5 SECONDS, src, progress = TRUE))
		to_chat(user, span_warning("¡No logras quitar \the [item_to_remove]!"))
		return SECONDARY_ATTACK_CANCEL_ATTACK_CHAIN

	user.visible_message(span_info("[user] quita \the <span class='bold'>[item_to_remove]</span> de \the [src]"), span_notice("Quitas \the <span class='bold'>[item_to_remove]</span> de \the [src]"))
	// Remove either headstone or gravestone
	if(istype(item_to_remove, /obj/item/gravedecor/headstone))
		if(item_to_remove.sourceitem)
			user.put_in_active_hand(new item_to_remove.sourceitem())
		else
			// We need to perserve custom_message and inscription
			var/obj/item/gravedecor/headstone/replacement = new item_to_remove.type()
			replacement.inscription = headstone.inscription
			replacement.custom_message = headstone.custom_message
			user.put_in_active_hand(replacement)
		headstone = null
	else if(istype(item_to_remove, /obj/item/gravedecor/gravefence))
		if(item_to_remove.sourceitem)
			user.put_in_active_hand(new item_to_remove.sourceitem())
		else
			user.put_in_active_hand(new item_to_remove.type())
		gravefence = null

	update_quality()
	update_appearance(UPDATE_ICON)
	return SECONDARY_ATTACK_CANCEL_ATTACK_CHAIN

/obj/structure/closet/dirthole/insertion_allowed(atom/movable/AM)
	if(istype(AM, /obj/structure/closet/crate/chest) || istype(AM, /obj/structure/closet/burial_shroud) || istype(AM, /obj/structure/closet/crate/coffin))
		for(var/mob/living/M in contents)
			return FALSE
		for(var/obj/structure/closet/C in contents)
			return FALSE
		return TRUE
	return ..()

/obj/structure/closet/dirthole/toggle(mob/living/user)
	return

/obj/structure/closet/dirthole/item_interaction(mob/living/user, obj/item/tool, list/modifiers)
	//If you want to add in more items that arent a gravedecor subtype but do have an associated gravedecoration, add them here.
	//In the future, an associated list can be made between any non-gravedecor items, and their associated decoration. We only have one such case, so that isnt necessary.
	if(istype(tool, /obj/item/grown/log/tree/stick))
		if(headstone)
			to_chat(user, "<span class='warning'>Esta tumba ya tiene una lapida.</span>")
			return ITEM_INTERACT_BLOCKING
		if(stage != DIRTHOLE_GRAVE)
			to_chat(user, "<span class='warning'>No puedo poner un marcador de tumba en una tumba abierta.</span>")
			return ITEM_INTERACT_BLOCKING

		playsound(src, 'sound/foley/bandage.ogg', 100, FALSE)
		if(!do_after(user, 10 SECONDS, src))
			return ITEM_INTERACT_BLOCKING

		//We're checking this istype twice in case any other headstone without the gravedecor path is added.
		if(istype(tool, /obj/item/grown/log/tree/stick))
			headstone = new /obj/item/gravedecor/headstone/crude(null, tool.type)

		if(pacify_coffin(src, user))
			user.visible_message(span_rose("[user] consagra [src]."), span_rose("Yo consagro [src]."))
			if(!is_consecrated)
				SEND_SIGNAL(user, COMSIG_GRAVE_CONSECRATED, src)
				record_round_statistic(STATS_GRAVES_CONSECRATED)

		update_quality()
		update_appearance(UPDATE_ICON)
		qdel(tool)
		return ITEM_INTERACT_SUCCESS

	if(istype(tool, /obj/item/gravedecor))
		return interaction_decor(tool, user)
	else if(istype(tool, /obj/item/weapon/shovel))
		return interaction_shovel(tool, user)
	else if(istype(tool, /obj/item/reagent_containers/glass/bucket))
		return attemptwatermake(tool, user)
	else if(!user.cmode && !is_consecrated && headstone && tool.wlength == WLENGTH_SHORT)
		if(!(tool.get_sharpness()))
			to_chat(user, span_warning("\The [tool] no es lo suficientemente afilado como para grabar \the [headstone] en \the [src] ¡Vaya!"))
			return ITEM_INTERACT_BLOCKING
		return inscribe(tool, user)

/obj/structure/closet/dirthole/proc/attemptwatermake(obj/item/reagent_containers/bucket, mob/living/user)
	if(!istype(user.used_intent, /datum/intent/splash))
		return ITEM_INTERACT_BLOCKING

	if(!bucket.reagents?.total_volume)
		return ITEM_INTERACT_BLOCKING

	if(!do_after(user, 10 SECONDS, src))
		return ITEM_INTERACT_BLOCKING

	var/datum/reagent/master_reagent = bucket.reagents.get_master_reagent()
	var/reagent_volume = master_reagent.volume
	if(!bucket.reagents.remove_reagent(master_reagent.type, clamp(master_reagent.volume, 1, 100)))
		return ITEM_INTERACT_BLOCKING

	var/turf/structure_turf = get_turf(src)
	var/turf/open/water/W = structure_turf.PlaceOnTop(/turf/open/water/river/creatable)
	if(!W) // how did this happen
		return ITEM_INTERACT_BLOCKING

	W.water_reagent = master_reagent.type
	W.water_volume = clamp(reagent_volume, 1, 100)
	W.handle_water()
	playsound(W, 'sound/foley/waterenter.ogg', 100, FALSE)
	QDEL_NULL(src)
	return ITEM_INTERACT_SUCCESS

/obj/structure/closet/dirthole/proc/inscribe(obj/item/sharp, mob/user)
	var/new_message = tgui_input_text(user, "¿Que te gustaria que estuviera inscrito en \the [headstone]?", "Inscripcion personalizada", headstone.custom_message, 150, TRUE)
	if(!new_message || new_message == headstone.custom_message)
		return ITEM_INTERACT_BLOCKING

	user.visible_message(span_info("[user] comienza a grabar un mensaje en \the [headstone] con \a [sharp]."), span_info("Comienzas a grabar un mensaje en \the [headstone]."), span_info("Escuchas a alguien tallando piedra."))
	playsound(src, pick('sound/combat/hits/onrock/onrock (1).ogg', 'sound/combat/hits/onrock/onrock (2).ogg', 'sound/combat/hits/onrock/onrock (3).ogg', 'sound/combat/hits/onrock/onrock (4).ogg'), 100)
	if(!do_after(user, 5 SECONDS, src, progress=TRUE, display_over_user=TRUE))
		return ITEM_INTERACT_BLOCKING

	user.visible_message(span_info("[user] termina de trabajar en \the [headstone]."), span_info("Terminas de grabar \the [headstone] con tu mensaje."))
	headstone.custom_message = new_message
	return ITEM_INTERACT_SUCCESS

/// Called by `attackby()`, handles interactions with gravedecor objects
/obj/structure/closet/dirthole/proc/interaction_decor(obj/item/gravedecor/tool, mob/user)
	if(istype(tool, /obj/item/gravedecor/headstone))
		if(headstone)
			to_chat(user, "<span class='warning'>Esta tumba ya tiene una lapida.</span>")
			return ITEM_INTERACT_BLOCKING
		if(stage != DIRTHOLE_GRAVE)
			to_chat(user, "<span class='warning'>No puedo poner una lapida en una tumba abierta.</span>")
			return ITEM_INTERACT_BLOCKING

		playsound(src, 'sound/foley/bandage.ogg', 100, FALSE)
		if(!do_after(user, 5 SECONDS, src))
			return ITEM_INTERACT_BLOCKING

		headstone = tool
		if(pacify_coffin(src, user))
			user.visible_message(span_rose("[user] consagra [src]."), span_rose("Yo consagro [src]."))
			if(!is_consecrated)
				SEND_SIGNAL(user, COMSIG_GRAVE_CONSECRATED, src)
				record_round_statistic(STATS_GRAVES_CONSECRATED)

		qdel(tool)
		update_quality()
		update_appearance(UPDATE_ICON)
		return ITEM_INTERACT_SUCCESS

	if(istype(tool, /obj/item/gravedecor/gravefence))
		if(gravefence)
			to_chat(user, "<span class='warning'>Esta tumba ya tiene una valla.</span>")
			return ITEM_INTERACT_BLOCKING
		if(stage != DIRTHOLE_GRAVE)
			to_chat(user, "<span class='warning'>No puedo poner una valla de cementerio en una tumba abierta.</span>")
			return ITEM_INTERACT_BLOCKING

		playsound(src, 'sound/foley/bandage.ogg', 100, FALSE)
		if(!do_after(user, 5 SECONDS, src))
			return ITEM_INTERACT_BLOCKING
		gravefence = tool

		qdel(tool)
		update_quality()
		update_appearance(UPDATE_ICON)
		return ITEM_INTERACT_SUCCESS

/// Called by `attackby()`. Handles interactions with shovels.
/obj/structure/closet/dirthole/proc/interaction_shovel(obj/item/weapon/shovel/attacking_shovel, mob/user)
	if(user.used_intent.type != /datum/intent/shovelscoop)
		return NONE

	if(attacking_shovel.heldclod)
		playsound(src,'sound/items/empty_shovel.ogg', 100, TRUE)
		if(stage == DIRTHOLE_PIT) //close grave
			if(!do_after(user, 5 SECONDS * attacking_shovel.toolspeed, src)) //can't have nice things can we
				return ITEM_INTERACT_BLOCKING
			stage = DIRTHOLE_GRAVE
			climb_offset = 10
			close()
			update_quality()
			var/founds
			for(var/atom/A in contents)
				founds = TRUE
				break
			if(!founds)
				stage = DIRTHOLE_DEEP
				climb_offset = 0
				open()
			update_appearance(UPDATE_ICON | UPDATE_NAME)
		else if(stage < DIRTHOLE_GRAVE)
			stage--
			climb_offset = 0
			update_appearance(UPDATE_ICON | UPDATE_NAME)
			if(stage == 0)
				qdel(src)
		QDEL_NULL(attacking_shovel.heldclod)
		attacking_shovel.update_appearance(UPDATE_ICON_STATE)
		return ITEM_INTERACT_SUCCESS

	if(stage == DIRTHOLE_PIT)
		var/turf/our_turf = get_turf(src)
		var/turf/under_turf = GET_TURF_BELOW(our_turf)
		if(under_turf && our_turf && isopenturf(under_turf))
			playsound(src,'sound/items/dig_shovel.ogg', 100, TRUE)
			user.visible_message("[user] comienza a excavar la parte inferior de [src]", "Comienzo a excavar el fondo de [src].")
			if(!do_after(user, 10 SECONDS * attacking_shovel.toolspeed, src))
				return ITEM_INTERACT_BLOCKING
			attacking_shovel.heldclod = new(attacking_shovel)
			attacking_shovel.update_appearance(UPDATE_ICON_STATE)
			playsound(our_turf,'sound/items/dig_shovel.ogg', 100, TRUE)
			our_turf.ScrapeAway(flags = CHANGETURF_INHERIT_AIR)
			qdel(src)
			return ITEM_INTERACT_BLOCKING
		to_chat(user, "<span class='warning'>Creo que es lo suficientemente profundo.</span>")
		return ITEM_INTERACT_SUCCESS

	playsound(src,'sound/items/dig_shovel.ogg', 100, TRUE)

	if(stage < DIRTHOLE_PIT)
		stage++
		attacking_shovel.heldclod = new /obj/item/natural/clod/dirt(attacking_shovel)
		attacking_shovel.update_appearance(UPDATE_ICON_STATE)
		update_appearance(UPDATE_ICON | UPDATE_NAME)
		return ITEM_INTERACT_SUCCESS

	if(stage == DIRTHOLE_GRAVE)
		if(gravequality >= 10 && !HAS_TRAIT(user, TRAIT_GRAVEROBBER)) // Are you sure you want to do this?
			to_chat(user, span_boldwarning("Sientes un escalofrio al empezar a cavar la tumba, como si algo <span class='god_necra'>antiguo</span> te estuviera observando... ¿Estas preparado para enfrentar las consecuencias si continuas?"))
		if(!do_after(user, 5 SECONDS * attacking_shovel.toolspeed, src)) // WE CANT HAVE NICE THINGS CAN WE
			return ITEM_INTERACT_BLOCKING
		stage = DIRTHOLE_PIT
		climb_offset = 0
		open()
		if(headstone)
			if(headstone.sourceitem)
				new headstone.sourceitem(get_turf(src))
			else
				// We need to perserve custom_message and inscription
				var/obj/item/gravedecor/headstone/replacement = new headstone.type(get_turf(src))
				replacement.inscription = headstone.inscription
				replacement.custom_message = headstone.custom_message
			headstone = null
		if(gravefence)
			if(gravefence.sourceitem)
				new gravefence.sourceitem(get_turf(src))
			else
				new gravefence.type(get_turf(src))
			gravefence = null
		if(is_consecrated)
			handle_curse(user)

		unstasis() // if no longer stage 4, unfreeze the bodies

		attacking_shovel.heldclod = new /obj/item/natural/clod/dirt(attacking_shovel)
		attacking_shovel.update_appearance(UPDATE_ICON_STATE)
		is_consecrated = FALSE // Unconsecrate.
		update_appearance(UPDATE_ICON | UPDATE_NAME)
		update_quality()
		adjust_grave_necra_devotion()
		return ITEM_INTERACT_SUCCESS

/// A blessed grave curses you if you don't have the graverobber trait, otherwise just sends alarms after a delay
/obj/structure/closet/dirthole/proc/handle_curse(mob/user)
	if(!ishuman(user))
		return

	var/mob/living/carbon/human/L = user
	if(HAS_TRAIT(L, TRAIT_GRAVEROBBER))
		var/robbing = TRUE
		var/message = "Realizo el rito secreto de ocultamiento, la Doncella no sabra de mi transgresion aqui."
		switch(L.patron?.type)
			if(/datum/patron/divine/necra)
				robbing = FALSE
				message = "Realizo el rito secreto de la exhumacion, por lo que la Doncella pasa por alto mi transgresion."
			if(/datum/patron/divine/pestra) //Special notices if you're of a particular faith.
				message = "Realizo el rito secreto de ocultamiento, Pestra me protege de la mirada divina mientras exhumo este cadaver para estudiarlo."
			if(/datum/patron/inhumen/matthios)
				message = "Realizo el rito secreto de la liberacion, la Doncella no se da cuenta cuando el ocupante de esta tumba es liberado."
			if(/datum/patron/inhumen/zizo)
				message = "Realizo el rito secreto de la contaminacion, la Doncella no puede hacer nada mas que observar mientras deshago los ritos en esta tumba."
		to_chat(user, span_info(message))
		if(robbing)
			record_featured_stat(FEATURED_STATS_CRIMINALS, user) //You aren't a Necran, even though you didn't get any consequences you're still a criminal.
			record_round_statistic(STATS_GRAVES_ROBBED)
			SEND_SIGNAL(user, COMSIG_GRAVE_ROBBED, user)
			if(gravequality >= 7)
				addtimer(CALLBACK(src, TYPE_PROC_REF(/obj/structure/closet/dirthole, robbery_alert), L), rand(20, 90) SECONDS) // Delayed alert
		return

	switch(gravequality)
		if(0 to 3)
			L.visible_message("<span class='warning'>A Cuando [L] abre la tumba, la estasis que se mantiene sobre ella se rompe, ¡liberando todo el tiempo almacenado!</span>", \
			"<span class='warning'>ATan pronto como excavo la tumba, ¡todo el tiempo almacenado en ella se libera! Puedo sentir que envejezco un poco...</span>", \
			"<span class='hear'> ¡Escucho un fuerte silbido! </span>")
			if(!L.has_status_effect(/datum/status_effect/debuff/cursed_t4) && !L.has_status_effect(/datum/status_effect/debuff/cursed_t3) && !L.has_status_effect(/datum/status_effect/debuff/cursed_t2))
				L.apply_status_effect(/datum/status_effect/debuff/cursed_t1)
		if(4 to 6)
			L.visible_message("<span class='warning'>A Cuando [L] abre la tumba, la estasis que se mantiene sobre ella se rompe, ¡liberando todo el tiempo almacenado!</span>", \
			"<span class='warning'>ATan pronto como excavo la tumba, ¡todo el tiempo almacenado en ella se libera! Me siento envejecer unos años...</span>", \
			"<span class='hear'> ¡Escucho un fuerte silbido! </span>")
			L.remove_status_effect(/datum/status_effect/debuff/cursed_t1)
			if(!L.has_status_effect(/datum/status_effect/debuff/cursed_t4) && !L.has_status_effect(/datum/status_effect/debuff/cursed_t3))
				L.apply_status_effect(/datum/status_effect/debuff/cursed_t2)
		if(7 to 9)
			L.visible_message("<span class='warning'>As [L] abre la tumba, la estasis que se mantiene sobre ella se rompe, ¡liberando todo el tiempo almacenado! \n\ [L] se congela en su lugar, mientras susurros de alarma revolotean en todas direcciones.</span>", \
			"<span class='warning'>¡Tan pronto como desentierro la tumba, todo el tiempo almacenado en su interior se libera! \n Aunque me congela en el lugar, puedo escuchar los susurros de alarma que se emiten en todas direcciones. </span>", \
			"<span class='hear'> ¡Escucho un fuerte silbido y luego una cacofonia de susurros! </span>")
			var/turf/T = get_turf(src)
			new /obj/effect/timestop(T, 2, 5 SECONDS, null, MAGIC_RESISTANCE_HOLY)
			L.remove_status_effect(/datum/status_effect/debuff/cursed_t1)
			L.remove_status_effect(/datum/status_effect/debuff/cursed_t2)
			if(!(L.has_status_effect(/datum/status_effect/debuff/cursed_t4)))
				L.apply_status_effect(/datum/status_effect/debuff/cursed_t3)
			robbery_alert() // Now the entire church knows what you done!
		if(10) // Max curse...
			var/obj/item/bodypart/left_arm = L.get_bodypart(BODY_ZONE_L_ARM)
			var/obj/item/bodypart/right_arm = L.get_bodypart(BODY_ZONE_R_ARM)
			if(((!left_arm || left_arm.skeletonized) && (!right_arm || right_arm.skeletonized)))
				L.visible_message("<span class='warning'>As [L] abre la tumba, la estasis que se mantiene sobre ella se rompe, ¡liberando todo el tiempo almacenado! \n\ [L] se congela en su lugar y susurros de alarma revolotean en todas direcciones.</span>", \
				"<span class='warning'>¡Tan pronto como exhumo la tumba, todo el tiempo almacenado en su interior se libera! \n Aunque me congela en el lugar, puedo sentir como mis brazos envejecen mientras susurros de alarma se propagan en todas direcciones. </span>", \
				"<span class='hear'> ¡Escucho un fuerte silbido y luego una cacofonia de susurros! </span>")
			else
				L.visible_message("<span class='warning'>As [L] abre la tumba, la estasis que se mantiene sobre ella se rompe, ¡liberando todo el tiempo almacenado! \n\ [L] se congela en su lugar, mientras sus brazos se marchitan hasta los huesos, y susurros de alarma revolotean en todas direcciones.</span>", \
				"<span class='warning'>ATan pronto como excavo la tumba, ¡todo el tiempo almacenado en ella se libera! </span>\n\ <span class='warning big'>Mientras me congela en el lugar, puedo sentir mis brazos marchitarse hasta los huesos mientras susurros de alarma salen en todas direcciones.</span>", \
				"<span class='hear'> ¡Escucho un fuerte silbido y luego una cacofonia de susurros! </span>")
				if(left_arm)
					var/obj/item/bodypart/part_to_bonify = L.get_bodypart(BODY_ZONE_L_ARM)
					part_to_bonify.skeletonize(FALSE)
				if(right_arm)
					var/obj/item/bodypart/part_to_bonify = L.get_bodypart(BODY_ZONE_R_ARM)
					part_to_bonify.skeletonize(FALSE)
				L.emote("painscream")
				L.update_body_parts()
			var/turf/T = get_turf(src)
			new /obj/effect/timestop(T, 2, 15 SECONDS, null, MAGIC_RESISTANCE_HOLY)
			L.remove_status_effect(/datum/status_effect/debuff/cursed_t1)
			L.remove_status_effect(/datum/status_effect/debuff/cursed_t2)
			L.remove_status_effect(/datum/status_effect/debuff/cursed_t3)
			L.apply_status_effect(/datum/status_effect/debuff/cursed_t4)
			robbery_alert() // Now the entire church knows what you done!
	record_featured_stat(FEATURED_STATS_CRIMINALS, user)
	record_round_statistic(STATS_GRAVES_ROBBED)
	SEND_SIGNAL(user, COMSIG_GRAVE_ROBBED, user)

/// Alerts all clergy (except non-necran acoyltes) of a robbery!
/obj/structure/closet/dirthole/proc/robbery_alert(mob/robber, delay = FALSE)
	var/robbery_location = capitalize(get_area_name(get_turf(src)))
	if(robber) // Graverobbers get a delay before the alert, to give them time to leave
		to_chat(robber, span_warning("Los ritos que realice en \the [src] me han dado tiempo, pero los susurros de los muertos perturbados finalmente lograron romper el silencio..."))

	for (var/mob/living/player in GLOB.player_list)
		if (player.stat == DEAD || isbrain(player))
			continue
		if (is_priest_job(player.mind.assigned_role) || (is_monk_job(player.mind.assigned_role) && player.patron?.type == /datum/patron/divine/necra) || istype(player.mind.assigned_role, /datum/job/templar) || istype(player.mind.assigned_role, /datum/job/gmtemplar) || istype(player.mind.assigned_role, /datum/job/undertaker))
			to_chat(player, span_crit("Los susurros velados susurran una gran blasfemia, una tumba muy bendecida esta siendo robada en [robbery_location], esto no puede quedar impune."))

/// All bodies buried as 'frozen' in time, Necra's gift to ensure their bodies cease to decay
/obj/structure/closet/dirthole/proc/stasis()
	for(var/mob/living/corpse in get_all_contents())
		if(corpse.stat == DEAD)
			ADD_TRAIT(corpse, TRAIT_STASIS, GRAVE_TRAIT)

/// Reverse of `statis()`
/obj/structure/closet/dirthole/proc/unstasis()
	for(var/mob/living/corpse in get_all_contents())
		if(corpse.stat == DEAD)
			REMOVE_TRAIT(corpse, TRAIT_STASIS, GRAVE_TRAIT)

/// Proc that looks for valid turf and puts a necran lily on it.
/obj/structure/closet/dirthole/proc/grow_lily()
	for(var/turf/foundturf in range(1, src))
		if(istype(foundturf, /turf/open/floor/dirt || /turf/open/floor/dirt/road || /turf/open/floor/grass)) //Turf the lily can grow on.
			if(!locate(/obj/structure) in foundturf)
				new /obj/structure/flora/grass/herb/necralily(foundturf)
				break

/obj/structure/closet/dirthole/take_contents()
	var/atom/L = drop_location()
	..()
	for(var/obj/structure/closet/crate/coffin/C in L)
		if(C != src && insert(C) == -1)
			break

/obj/structure/closet/dirthole/close(mob/living/user)
	if(!opened || !can_close(user))
		return FALSE
	take_contents()
	for(var/mob/A in contents)
		if((A.stat) && (istype(A, /mob/living/carbon/human)))
			var/mob/living/carbon/human/B = A
			B.buried = TRUE
	opened = FALSE
	return TRUE

/obj/structure/closet/dirthole/dump_contents()
	for(var/mob/A in contents)
		if((!A.stat) && (istype(A, /mob/living/carbon/human)))
			var/mob/living/carbon/human/B = A
			B.buried = FALSE
	..()

/obj/structure/closet/dirthole/open(mob/living/user)
	if(opened)
		return
	if(stage == DIRTHOLE_GRAVE)
		stage = DIRTHOLE_PIT
		climb_offset = 0
	opened = TRUE
	dump_contents()
	update_appearance(UPDATE_ICON | UPDATE_NAME)
	return TRUE

/// Proc to update `quality`, should be called when `headstone` or `gravefence` is modified, and other cases where the condition of the grave has changed
/obj/structure/closet/dirthole/proc/update_quality()
	gravequality = 0
	if(stage != DIRTHOLE_GRAVE) // If not a complete grave, no quality
		return
	if(bonusquality)
		gravequality += bonusquality

	// Check if area is fit for burials
	var/area/A = get_area(src)
	if(A.burial_grounds)
		gravequality += 1

	// Calculate damage to buried bodies and provide malus if too damaged.
	var/bodyquality = 0
	for(var/mob/living/carbon/human/corpse in get_all_contents()) // We only care about humans
		// No head? -1 point
		if(!(corpse.get_bodypart(BODY_ZONE_HEAD)))
			bodyquality -= 1

		// Too much brute or burn damage? -1 point
		if(corpse.getBruteLoss() >= 75 || corpse.getFireLoss() >= 75)
			bodyquality -= 1

	gravequality += bodyquality

	if(headstone)
		var/headquality = headstone.decorationquality
		for(var/mob/living/corpse in contents)
			if(corpse.patron.type in headstone.patrons)
				headquality = 3
		gravequality += headquality

	if(gravefence)
		var/fencequality = gravefence.decorationquality
		for(var/mob/living/corpse in contents)
			if(corpse.patron.type in gravefence.patrons)
				fencequality = 3
		gravequality += fencequality
	for(var/obj/structure/closet/crate/coffin/coffin in contents)
		gravequality += 1
		if(coffin.consecrated)
			gravequality += 2
	for(var/obj/structure/closet/burial_shroud/shroud in contents)
		gravequality += 1

	gravequality = clamp(gravequality, 0, 10)
	adjust_grave_necra_devotion()

/// Proc that adjusts every necran's devotion passive gain based on grave quality, up to global max
/obj/structure/closet/dirthole/proc/adjust_grave_necra_devotion()
	var/new_devotion = 0
	var/change = 0
	if(no_devotion)
		return

	// Step 1: Calculate new_devotion
	if(gravequality >= 7 && is_consecrated) // T3 and higher graves get devotion, otherwise is 0
		new_devotion = GRAVE_DEVOTION_INCREMENT * (gravequality - 6) // For each level of quality above 6, increment.

	// Step 2: Compare new_devotion with necra_devotion_gain to find change.
	change = new_devotion - necra_devotion_gain
	necra_devotion_gain = new_devotion

	if(change == 0) // Nothing to adjust
		return

	// Step 3: Implement change
	// Update potential devotion gain
	GLOB.potential_grave_devotion_gain += change

	// Adjust devotion gain for each gravetender, up to a max
	for (var/mob/living/carbon/human/player in GLOB.player_list)
		if (player.stat == DEAD || isbrain(player) || !player.cleric)
			continue
		if(player.patron?.type == /datum/patron/divine/necra) // Person must be able to use miracles and worship Necra
			// Grab their devotion
			var/datum/devotion/devotion = player.cleric
			var/current_passive_gain = devotion.passive_devotion_gain
			var/devotion_change = change

			if(current_passive_gain == GRAVE_DEVOTION_GLOBAL_MAX && GLOB.potential_grave_devotion_gain < GRAVE_DEVOTION_GLOBAL_MAX) // At max and we are not reducing it, skip
				continue

			// We grab the potential_grave_devotion_gain and have each gravetender update to reach it (or stopped by max)
			// potential_grave_devotion_gain is less than max
			if(GLOB.potential_grave_devotion_gain <= GRAVE_DEVOTION_GLOBAL_MAX)
				devotion_change = GLOB.potential_grave_devotion_gain - current_passive_gain // Have their devotion generation match potential_grave_devotion_gain by calculating the difference and adding/decreasing

			else // potential_grave_devotion_gain is over MAX, have devotion set to max
				devotion_change = GRAVE_DEVOTION_GLOBAL_MAX - current_passive_gain

			devotion.update_passive_devotion(devotion_change)

/obj/structure/closet/dirthole/update_icon_state()
	. = ..()
	switch(stage)
		if(DIRTHOLE_SHALLOW)
			icon_state = "hole1"
		if(DIRTHOLE_DEEP)
			icon_state = "hole2"
		if(DIRTHOLE_PIT)
			icon_state = "grave"
		if(DIRTHOLE_GRAVE)
			icon_state = "gravecovered"

/obj/structure/closet/dirthole/update_overlays()
	. = ..()
	if(stage < DIRTHOLE_PIT)
		return
	else if(stage == DIRTHOLE_PIT)
		. += mutable_appearance(icon, "grave_above", ABOVE_MOB_LAYER)

	if(is_consecrated)
		switch(gravequality)
			if(0 to 3)
				. += mutable_appearance('icons/turf/constructed/grave.dmi', "consecration1", 2.92)
			if(4 to 6)
				. += mutable_appearance('icons/turf/constructed/grave.dmi', "consecration2", 2.92)
			if(7 to 9)
				. += mutable_appearance('icons/turf/constructed/grave.dmi', "consecration3", 2.92)
			if(10)
				. += mutable_appearance('icons/turf/constructed/grave.dmi', "consecration4", 2.92)
	if(headstone)
		. += mutable_appearance('icons/turf/constructed/grave.dmi', headstone.icon_state, 2.91)
	if(gravefence)
		. += mutable_appearance('icons/turf/constructed/grave.dmi', gravefence.icon_state, 2.9)

/obj/structure/closet/dirthole/update_name(updates)
	. = ..()
	switch(stage)
		if(DIRTHOLE_SHALLOW, DIRTHOLE_DEEP)
			name = "agujero"
		if(DIRTHOLE_PIT)
			name = "fosa"
		if(DIRTHOLE_GRAVE)
			name = "tumba"

/obj/structure/closet/dirthole/relaymove(mob/user)
	if(user.stat || !isturf(loc) || !isliving(user))
		return
	if(!IS_DEADITE(user))
		if(message_cooldown <= world.time)
			message_cooldown = world.time + 50
			to_chat(user, "<span class='warning'> ¡Estoy atrapado! </span>")
		return
	container_resist(user)

#undef GRAVE_DEVOTION_INCREMENT
#undef GRAVE_DEVOTION_GLOBAL_MAX
